# This is a basic workflow to help you get started with Actions

name: debug windows Qt5 CI

# Controls when the workflow will run
on:

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: windows-2019

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2

      - name: Install Qt5
        # 使用外部action。这个action专门用来安装Qt
        uses: jurplel/install-qt-action@v2
        with:
          # Version of Qt to install
          version: 5.15.2
          # Target platform for build
          # target: ${{ matrix.qt_target }}
          arch: win64_msvc2019_64
          cached: 'false'
          aqtversion: '==2.0.5'

      # Runs a single command using the runners shell
      - name: debug
        uses: mxschmitt/action-tmate@v3