# This is a basic workflow to help you get started with Actions

name: dev CI

# Controls when the action will run.
on:
  workflow_dispatch:
  # Allows you to run this workflow manually from the Actions tab
  # workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: macos-11.0

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
<<<<<<< HEAD
      - uses: shaowenchen/debugger-action@v2
        name: debugger
        timeout-minutes: 30
        continue-on-error: true
        with:
          frp_server_addr: ${{ secrets.FRP_SERVER_ADDR }}
          frp_server_port: ${{ secrets.FRP_SERVER_PORT }}
          frp_token: ${{ secrets.FRP_TOKEN }}
          ssh_port: ${{ secrets.FRP_SSH_PORT }}
=======
    - name: SSH connection to Actions
      uses: p3terx/debugger-action@master
>>>>>>> 9630e9de88fafe1c75a15bac1e387f7a0b88ded3
