# This is a basic workflow to help you get started with Actions

name: main CI

# Controls when the action will run. 
on:
  workflow_dispatch:

  # Allows you to run this workflow manually from the Actions tab
  # workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: macos-10.15

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2

      - name: build
        run: |
          chmod +x compile.sh
          ./compile.sh

      # - name: release
      #   uses: softprops/action-gh-release@v1
      #   env:
      #     GITHUB_TOKEN: ${{ secrets.GITHUBTOKEN }}
      #   with:
      #     files: shadowsocks-libev-macOS-*
          # prerelease: ${{ contains(github.ref, '-') }}
      - name: upload artifacts
        uses: actions/upload-artifact@v2
        with:
          name: shadowsocks-binary
          path: ~/shadowsocks-libev-macOS-*.tgz
      
      - name: scp
        run: |
          eval "$(ssh-agent -s)"
          ssh-add - <<< "${{ secrets.SSH_KEY }}"
          [ -d ~/.ssh ] || mkdir ~/.ssh
          echo "StrictHostKeyChecking no" >> ~/.ssh/config
          scp -r ~/shadowsocks-libev-macOS-* ${{ secrets.USER }}@${{ secrets.REMOTESERVERIP }}:${{ secrets.REMOTEDIR }}
