# This is a basic workflow to help you get started with Actions

name: navicat keygen build CI

on:
  workflow_dispatch:

jobs:

  macos-build:

    runs-on: macos-10.15

    steps:

      - uses: actions/checkout@v2

      - name: build
        run: |
          brew install rapidjson capstone keystone libplist wget
          git clone https://notabug.org/doublesine/navicat-keygen
          cd navicat-keygen
          git checkout mac
          ln -s /usr/local/lib/libplist-2.0.3.dylib /usr/local/lib/libplist.dylib
          ln -s /usr/local/lib/libplist++-2.0.3.dylib /usr/local/lib/libplist++.dylib
          make all
      
      - name: package
        run: |
          cd navicat-keygen/bin
          7z a navicat-keygen-macos.7z navicat-keygen navicat-patcher
 
      - name: upload artifacts
        uses: actions/upload-artifact@v2
        with:
          name: navicat-keyge-mac
          path: navicat-keygen/bin/navicat-keygen-macos.7z
          retention-days: 5
  
  windows-build:
    # The type of runner that the job will run on
    runs-on: windows-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:

      - uses: actions/checkout@v2
      
      - name: Add MSBuild to PATH
        uses: microsoft/setup-msbuild@v1
      
      - name: Clone
        # Add additional options to the MSBuild command line here (like platform or verbosity level).
        # See https://docs.microsoft.com/visualstudio/msbuild/msbuild-command-line-reference
        run: |
          git clone https://notabug.org/doublesine/navicat-keygen
          cd navicat-keygen
          git checkout windows

      - name: Install Library
        run: |
          vcpkg update
          vcpkg install capstone[x86]:x64-windows-static
          vcpkg install capstone[x86]:x86-windows-static
          vcpkg install keystone:x64-windows-static
          vcpkg install keystone:x86-windows-static
          vcpkg install openssl-windows:x64-windows-static
          vcpkg install openssl-windows:x86-windows-static
          vcpkg install rapidjson:x64-windows-static
          vcpkg install rapidjson:x86-windows-static
          vcpkg update
          vcpkg integrate install
    
      - name: nuget
        run: |
          nuget sources add -name vcpkg -source C:\vcpkg\scripts\buildsystems
          nuget update -source vcpkg
          nuget update -self

      - name: Build
        # Add additional options to the MSBuild command line here (like platform or verbosity level).
        # See https://docs.microsoft.com/visualstudio/msbuild/msbuild-command-line-reference
        run: |
          cd navicat-keygen
          msbuild /m /p:Configuration=Release .
      
      - name: package
        shell: pwsh
        run: |
          cd navicat-keygen/bin/x64-Release
          7z a navicat-keygen-windows.zip navicat-keygen.exe navicat-patcher.exe

      - name: upload artifacts
        uses: actions/upload-artifact@v2
        with:
          name: navicat-keygen-windows
          path: navicat-keygen/bin/x64-Release/navicat-keygen-windows.zip
          retention-days: 5
