# This is a basic workflow to help you get started with Actions

name: navicat CI

on:
  workflow_dispatch:

jobs:

  build:

    runs-on: macos-10.15

    steps:

      - uses: actions/checkout@v2

      - name: build
        run: |
          brew install rapidjson capstone keystone libplist wget
          git clone https://notabug.org/doublesine/navicat-keygen
          cd navicat-keygen
          git checkout mac
          [ -t /usr/local/lib/libplist-2.0.3.dylib ] || ln -s /usr/local/lib/libplist-2.0.3.dylib /usr/local/lib/libplist.dylib
          [ -t /usr/local/lib/libplist++-2.0.3.dylib ] || ln -s /usr/local/lib/libplist++-2.0.3.dylib /usr/local/lib/libplist++.dylib
          make all
          mv bin navicat-keygen
          gtar -zcvf navicat-keygen.tgz navicat-keygen
          cp navicat-keygen.tgz ~/
      
      # - name: test
      #   run: |
      #     wget --no-check-certificate https://download3.navicat.com/download/navicat150_premium_en.dmg
      #     hdiutil attach navicat150_premium_en.dmg
      #     cd /Volumes/Navicat\ Premium/
      #     cp -r Navicat\ Premium.app Applications/

      - name: scp
        run: |
          eval "$(ssh-agent -s)"
          ssh-add - <<< "${{ secrets.SSH_KEY }}"
          [ -d ~/.ssh ] || mkdir ~/.ssh
          echo "StrictHostKeyChecking no" >> ~/.ssh/config
          scp -r ~/navicat-keygen.tgz ${{ secrets.USER }}@${{ secrets.REMOTESERVERIP }}:${{ secrets.REMOTEDIR }}
