# This is a basic workflow to help you get started with Actions

name: next-terminal build CI

# Controls when the action will run. 
on:
  workflow_dispatch:

  # Allows you to run this workflow manually from the Actions tab
  # workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2

      - uses: actions/setup-go@v2
        with:
          go-version: '1.18.3'

      - name: build
        run: |
          git clone https://github.com/dushixiang/next-terminal
          cd next-terminal
          cd web
          npm install
          npm update
          cd ../
          chmod +x build.sh
          ./build.sh

      - name: upload artifacts
        uses: actions/upload-artifact@v2
        with:
          name: next-terminal
          path: next-terminal/next-terminal
          retention-days: 5