# This is a basic workflow to help you get started with Actions

name: CI

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the main branch
  push:
    branches: [ main ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: macos-10.15

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2

      # Runs a single command using the runners shell
      - name: build
        run: |
          git clone https://github.com/shanyungyang/esxi-unlocker.git
          cd esxi-unlocker
          ./esxi-build.py
          ls -al
          eval "$(ssh-agent -s)"
          ssh-add - <<< "${{ secrets.SSH_KEY }}"
          [ -d ~/.ssh ] || mkdir ~/.ssh
          echo "StrictHostKeyChecking no" >> ~/.ssh/config
          scp -r esxi-unlocker-*.tgz ${{ secrets.USER }}@${{ secrets.REMOTESERVERIP }}:${{ secrets.REMOTEDIR }}
