# This is a basic workflow to help you get started with Actions

name: VyOS lts build CI

# Controls when the action will run. 
on:
  workflow_dispatch:

  # Allows you to run this workflow manually from the Actions tab
  # workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2

      - name: build
        run: |
          cd vyos-build
          chmod +x vyos-build.sh
          ./vyos-build.sh
          sudo chown -R runner:runner .

      - name: minio-client install
        run: |
          curl https://dl.min.io/client/mc/release/linux-amd64/mc --create-dirs -o $HOME/minio-binaries/mc
          chmod +x $HOME/minio-binaries/mc
          export PATH=$PATH:$HOME/minio-binaries/
          mc --help
      
      - name: minio upload
        run: |
          export PATH=$PATH:$HOME/minio-binaries/
          mc alias set minio ${{ secrets.MINIO_ENDPOINT }} ${{ secrets.MINIO_ACCESS_KEY }} ${{ secrets.MINIO_SECRET_KEY }}
          mc cp vyos-build/vyos-build/build/vyos-1.3.3-lts.iso minio/public
          mc cp vyos-build/vyos-build/build/vyos-1.3.3-lts-signed.ova minio/public
                
      - name: upload artifacts
        uses: actions/upload-artifact@v2
        with:
          name: vyos_vmware_image-signed
          path: vyos-build/vyos-build/build/vyos_vmware_image-signed.ova
          retention-days: 5
          