# This is a basic workflow to help you get started with Actions

name: VyOS lts build CI

# Controls when the action will run. 
on:
  workflow_dispatch:

  # Allows you to run this workflow manually from the Actions tab
  # workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2

      - name: build
        run: |
          cd vyos-build
          chmod +x vyos-build.sh
          ./vyos-build.sh
          sudo chown -R runner:runner .
      
      - name: upload artifacts
        uses: actions/upload-artifact@v2
        with:
          name: vyos_vmware_image-signed
          path: vyos-build/vyos-build/build/vyos_vmware_image-signed.ova
          retention-days: 5
          